orbs:
  rookout-node: rookout/rookout-node@0.0.7

jobs:
  main_flow:
    docker:
      - image: circleci/node:10
    working_directory: ~/circleci-rookout
    steps:
      - checkout:
          path: ~/circleci-rookout
      - run: "npm install"
      - rookout-node/run_script:
          users_script: "node_modules/jest/bin/jest.js ."
          rookout_tags: "${CIRCLE_BRANCH}"



version: 2.1
workflows:
  version: 2
  build_and_test:
    jobs:
      - main_flow